 version: '2'
 services:
   scribd:
     build: .
     ports:
      - "8080:8080"
     volumes:
      - .:/go/src/app
     links:
      - postgres
   postgres:
     image: postgres
     ports:
       - "5432:5432" # Remove before deploying these images (this opens the 5432 port to the outside)
     environment:
      - POSTGRES_PASSWORD=c0g1n0v
      - POSTGRES_USER=scribd
     volumes:
      - ./data:/var/lib/postgresql/data
      - ./sqlinit:/docker-entrypoint-initdb.d
